### ISSUE TITLE
schematics ?

### ISSUE THREAD

**Issue by BradWalker** [lyusupov/UAT-test-signal#2]
Nice project..

I'm interested in knowing if you will make the schematics and gerbers available like  you mentioned..

I'm thinking this would be helpful for a research project I'm working on..

-brad w.

**Comment by lyusupov** [comment]
There is one known errata in schematics/PCB layout that affects one of the module use cases.
I can live with it, but it makes sense to fix it before release for public.
Since it is low priority task - there is no rush for doing that soon.

What is wrong for your research project to deal with the LaunchPad ?
